"""Agregada tabla bitacora_evento

Revision ID: de14b8c9269b
Revises: 8b18c229d666
Create Date: 2022-09-15 12:00:14.672497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de14b8c9269b'
down_revision = '8b18c229d666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bitacora_evento', sa.Column('fecha', sa.DATE(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bitacora_evento', 'fecha')
    # ### end Alembic commands ###
