"""Nuevos atributos de anfitrion y evento para la landing page

Revision ID: f2a95e20ba5a
Revises: 8e6c9829c8fa
Create Date: 2022-10-15 06:42:19.507310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a95e20ba5a'
down_revision = '8e6c9829c8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
