version: '3'
services:
  ventu-frontend:
    build:
      context: ./ventu-frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./ventu-frontend:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0 --poll=1000
    networks:
      - qsm-red

  ventu-backend:
    build:
      context: ./ventu-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./ventu-backend:/app
    environment:
      - FLASK_ENV=development  # Establece la variable de entorno FLASK_ENV en "development"
    command: flask run --host 0.0.0.0
    networks:
      - qsm-red

networks:
  qsm-red:
    external: true
