"""Agregada tabla bitacora_evento

Revision ID: 8b18c229d666
Revises: 69d7b6a3fe17
Create Date: 2022-09-15 11:51:13.195496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b18c229d666'
down_revision = '69d7b6a3fe17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignacion_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_usuario', sa.Integer(), nullable=True),
    sa.Column('fk_eventos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_eventos'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacora_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('fk_evento', sa.Integer(), nullable=True),
    sa.Column('fk_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_evento'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bitacora_evento')
    op.drop_table('asignacion_eventos')
    # ### end Alembic commands ###
